package com.example.tinderclone.util

const val DATA_USERS = "Users"
const val DATA_NAME = "name"
const val DATA_EMAIL = "email"
const val DATA_AGE = "age"
const val DATA_GENDER = "gender"
const val DATA_GENDER_PREFERENCE = "preferredGender"
const val GENDER_FEMALE = "female"
const val GENDER_MALE = "male"
const val DATA_IMAGE_URL = "imageUrl"
const val DATA_SWIPES_LEFT = "swipesLeft"
const val DATA_SWIPES_RIGHT = "swipesRight"
const val DATA_MATCHES = "matches"
const val DATA_CHATS = "Chats"
const val DATA_MESSAGES = "Messages"